In [ ]:
pip install pandas

In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [ ]:
df

In [ ]:
df.iloc[0:3,0:3]

In [ ]:
df.at[0,'age']

In [ ]:
df.iat[2,1]

In [ ]:
df[df['age']>30]

In [ ]:
df[(df['age']>28) & (df['city']=='NY')]

In [ ]:
df[(df['age']>28) | (df['city']=='LA')]

In [ ]:
df[(df['city']=='NY') | (df['name']=='David')]

In [ ]:
df[(df['city']=='NY') | (df['name']=='Bob')]

In [ ]:
df[df['city'].isin(['NY','SF'])]

In [ ]:
df[df['city'].isin(['NY','LA'])]

In [ ]:
df.query('age >28 and city=="NY"')

In [ ]:
df.query('age >28 or city=="NY"')

In [ ]:
df.where(df['age']>28)

In [ ]:
df.where(df['age']>30)

In [ ]:
df.mask(df['age']>28)

In [ ]:
df.mask(df['age']>30)

In [4]:
df2=df.copy()

In [ ]:
df2

In [ ]:
df2['senior']=df2['age']>30
df2

In [ ]:
df2['age_plus5']=df2['age']+5
df2

In [ ]:
df2.rename(columns={'city':'location'},inplace=True)
df2

In [ ]:
df2

In [5]:
df2.drop(index=0,inplace=False)

C:\Users\premk\AppData\Local\Temp\ipykernel_6860\1890677905.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df2.drop(index=0,inplace=False)

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [7]:
df2.insert(1,'id',range(len(df2)))

In [8]:
df2

      name  id  age city
0    Alice   0   25   NY
1      Bob   1   30   LA
2  Charlie   2   35   SF
3    David   3   40   NY

In [11]:
df2.assign(double_age=df2['age']*2)

      name  id  age city  double_age
0    Alice   0   25   NY          50
1      Bob   1   30   LA          60
2  Charlie   2   35   SF          70
3    David   3   40   NY          80

### Handling Missing Values

In [12]:
df_na=pd.DataFrame({'a':[1,np.nan,3],'b':[np.nan,2,3]})

In [13]:
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

In [15]:
df_na.isna() #Boolean mask of missing values

       a      b
0  False   True
1   True  False
2  False  False

In [17]:
df_na.notna() #revers of .isna()

       a      b
0   True  False
1  False   True
2   True   True

In [19]:
df_na.isnull().sum() #counts missing values by cloumns

a    1
b    1
dtype: int64

In [20]:
df_na.dropna()

     a    b
2  3.0  3.0

In [27]:
df_na.dropna(axis=1) #use to drop columns

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [26]:
df_na.fillna(0.5) #fill null values

     a    b
0  1.0  0.5
1  0.5  2.0
2  3.0  3.0

In [28]:
df_na.ffill() #forward fill

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

In [29]:
df_na.bfill() #backward fill

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

In [37]:
df1=pd.DataFrame({
    'name':['Alice','Bob','Charlie','David'],
    'age':[25,30,35,40],
    'city':['NY','LA','SF','NY']
})

In [38]:
df1

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [39]:
df1.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [40]:
df1.sort_values(['city','age'],ascending=[True,False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

In [46]:
df1.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [45]:
df1['age'].rank()

0    1.0
1    2.0
2    3.0
3    4.0
Name: age, dtype: float64

In [47]:
df1.nlargest(2,'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

In [48]:
df1.nsmallest(3,'age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

### Aggregation and Statistics

In [49]:
df1['age'].sum(), df1['age'].mean(), df1['age'].median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

In [50]:
df1['age'].std(), df1['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

In [51]:
df1['age'].max(),df1['age'].min()

(np.int64(40), np.int64(25))

In [52]:
df1['age'].count()

np.int64(4)

In [56]:
df1.agg({'age':['mean','max','min']}) #apply a multiple aggregation functions at are

       age
mean  32.5
max   40.0
min   25.0

In [55]:
df1.corr(numeric_only=True)

     age
age  1.0

In [57]:
df1['city'].mode()

0    NY
Name: city, dtype: str

In [2]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [8]:
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2

In [9]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [10]:
df.to_excel('data.xlsx',index=False)
pd.read_excel('data.xlsx')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY